dist: trusty
sudo: false
language: go
go:
- 1.9.2
- master

install:
- go get github.com/kardianos/govendor

script:
- make test
- make vendor-status
- make vet

matrix:
  fast_finish: true
  allow_failures:
  - go: master
